# Generated by Django 2.2.7 on 2020-07-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reputation',
            field=models.FloatField(default=0),
        ),
    ]
