# Generated by Django 3.0.7 on 2020-07-04 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('is_answer_deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.IntegerField(blank=True)),
                ('field2', models.IntegerField(null=True)),
                ('field3', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='is_question_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
